todo/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "todo"
urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', views.index, name='index'),
    path('', views.overview, name="overview"),
    path('<int:todo_id>/', views.detail, name="detail"),
    path('<int:todo_id>/status_change', views.status_change, name="status_change"),
]

todo_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls')),
]

todo/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib import admin

#https://code.tutsplus.com/articles/intro-to-django-building-a-to-do-list--net-2871

class Category(models.Model):
    name = models.CharField(max_length=100)
    
class Todo(models.Model): #Table name, has to wrap models.Model to get the functionality of Django.
    status_choices = [
        ("D", "Done"),
        ("T", "Todo"),
        ("C", "Cancelled"),
    ]
         
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField() #Like a TEXT field
    deadline = models.DateTimeField(null=True)
    status = models.CharField(max_length=1, choices=status_choices, default="T")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    created = models.DateTimeField() #Like a DATETIME field
    def __str__(self):
        return f"{self.name} {self.category} {self.status} {self.deadline}"
    
    def __unicode__(self): #Tell it to return as a unicode string (The name of the to-do item) rather than just Object.
        return self.name
        

todo/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse
from todo.models import Todo
from django.shortcuts import render

def index(request):
    #return HttpResponse("Hello, world. You're at the todo index.")
    items = todo.objects.all() #ORM queries the database for all of the to-do entries.
    return render(request,'todo/index.html', {'items': items}) #Responds with passing the object items (contains info from the DB) to the template index.html



def detail(request, todo_id):
  # do something with the question_id
  todo = get_object_or_404(Todo, pk=todo_id)
  return render(request, "todo/detail.html", {'todo' : todo})

def overview(request):
    todos = Todo.objects.all()
    return render(request, 'todo/overview.html', {"todos" : todos})
    
def status_change(request, todo_id):
    todo = get_object_or_404(Todo, pk=todo_id)
    todo.status = request.POST["status"] # selber name wie im <select>-tag
    todo.save()
    return HttpResponseRedirect(reverse('todo:overview'))
    
def new(request):
    name = request.POST["name"]
    description = request.POST["description"]
    status = request.POST["status"]
    deadline = request.POST["deadline"]
    category = Category.objects.get(pk=request.POST["category"])

    print(name, description, status, deadline, category)

    Todo.objects.create(name=name,
                        description=description,
                        status=status,
                        deadline=deadline,
                        category=category)
    return HttpResponseRedirect(reverse('todo:overview'))

todo/templates/todo/index.html
<h2>todo</h2>
 
{% for x in items %}
<p>{{ x.name }} - {{ x.created|date:"D d M Y" }}</p>
 
<p>{{ x.description }}</p>
<hr />
{% endfor %}

todo/templates/todo/overview.html
<h1>Todo-List</h1>
<table>
  <tr><th>Name</th><th>Status</th><th>Deadline</th><th>Action</th></tr>
  {% for todo in todos %}
  <tr>
    <td><a href="{% url 'todo:detail' todo.id %}">{{todo.name}}</a></td>
    <td>{{todo.status}}</td>
    <td>{{todo.deadline}}</td>
    <td>
      <form action="{% url 'todo:status_change' todo.id %}" method="post">
        {% csrf_token %}
        <select name="status">
          {% for item in todo.status_choices %}
          <option value="{{item.0}}">{{item.1}}</option>
          {% endfor %}
          </select>
        <input type="submit" value="Change">
      </form>
    </td>
  </tr>
  {% endfor %}
</table>

<form action="{% url 'todo:new' %}" method="post">
  {% csrf_token %}
  <label>Name</label><input type="text" name="name"><br>

  <label>Beschreibung</label><input type="text" name="description"><br>

  <label>Status</label>
  <select name="status">
    {% for item in status_choices %}
      <option value="{{item.0}}">{{item.1}}</option>
    {% endfor %}
  </select><br>

  <label>Kategorie</label>
  <select name="category">
    {% for item in categories %}
    <option value="{{item.id}}">{{item}}</option>
    {% endfor %}
  </select><br>

  <label>Deadline</label>
  <input type="date" name="deadline">
  <input type="submit" value="Anlegen">
</form>